name: document_similarity
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - gensim=4.1.2
  - tqdm=4.64.1
  - pandas=1.4.4
  - nltk=3.7
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - ipywidgets=7.6.5
  - pip:
    - datasketch==1.5.8