#!/usr/bin/env python3
name: document_similarity

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - gensim=4.1
  - tqdm=4.64
  - pandas=2.1
  - openpyxl=3.0.10
  - nltk=3.7
  - matplotlib=3.5.2
  - seaborn=0.12
  - ipywidgets=8.1
  - bokeh=3.3
  - swifter=1.3.5
  - numpy=1.26
  - ipython=8.20
  - pip
  - pip:
    - datasketch==1.5.8
    - atap-corpus-loader==1.1.3
