#!/usr/bin/env python3
name: document_similarity

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9.13
  - gensim=4.1.2
  - tqdm=4.64.1
  - pandas
  - openpyxl=3.0.10
  - nltk=3.7
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - ipywidgets=8.0.2
  - bokeh=2.4.3
  - pip
  - pip:
    - datasketch==1.5.8